[package]
name = "get_avg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "get_avg"
path = "src/main.rs"

[dependencies]
colored = "2.1.0"
